package com.elwin013.arweb.dao.model;

// Generated 2014-12-15 22:55:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "Authorities", catalog = "m12173_ar_web")
public class Authorities implements java.io.Serializable {
	private static final long serialVersionUID = -3047662047582007434L;
	
	private Integer idAuthority;
	private User user;
	private String authority;

	public Authorities() {
	}

	public Authorities(String authority) {
		this.authority = authority;
	}

	public Authorities(User user, String authority) {
		this.user = user;
		this.authority = authority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAuthority", unique = true, nullable = false)
	public Integer getIdAuthority() {
		return this.idAuthority;
	}

	public void setIdAuthority(Integer idAuthority) {
		this.idAuthority = idAuthority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "authority", nullable = false, length = 31)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
