package com.elwin013.arweb.dao.model;

// Generated 2014-12-15 22:55:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "Device", catalog = "m12173_ar_web")
public class Device implements java.io.Serializable {
	private static final long serialVersionUID = -7960037449665345290L;
	
	private Integer idDevice;
	private String udid;
	private String connKey;
	private Set<Spot> spots = new HashSet<Spot>(0);

	public Device() {
	}

	public Device(String connKey) {
		this.connKey = connKey;
	}

	public Device(String udid, String connKey, Set<Spot> spots) {
		this.udid = udid;
		this.connKey = connKey;
		this.spots = spots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDevice", unique = true, nullable = false)
	public Integer getIdDevice() {
		return this.idDevice;
	}

	public void setIdDevice(Integer idDevice) {
		this.idDevice = idDevice;
	}

	@Column(name = "udid", length = 127)
	public String getUdid() {
		return this.udid;
	}

	public void setUdid(String udid) {
		this.udid = udid;
	}

	@Column(name = "connKey", nullable = false, length = 10)
	public String getConnKey() {
		return this.connKey;
	}

	public void setConnKey(String connKey) {
		this.connKey = connKey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "device")
	public Set<Spot> getSpots() {
		return this.spots;
	}

	public void setSpots(Set<Spot> spots) {
		this.spots = spots;
	}

}
