package com.elwin013.arweb.dao.model;

// Generated 2014-12-15 22:55:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Spot generated by hbm2java
 */
@Entity
@Table(name = "Spot", catalog = "m12173_ar_web")
public class Spot implements java.io.Serializable {
	private static final long serialVersionUID = -227004886566170723L;
	
	private Integer idSpot;
	private Device device;
	private User user;
	private SpotType spotType;
	private Date creationDate;
	private String description;
	private String name;
	private BigDecimal latitude;
	private BigDecimal logitude;
	private BigDecimal accuracy;
	private byte[] image;
	private Boolean isPublic;

	public Spot() {
	}

	public Spot(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Spot(Device device, User user, SpotType spotType, Date creationDate,
			String description, String name, BigDecimal latitude,
			BigDecimal logitude, BigDecimal accuracy, byte[] image,
			Boolean isPublic) {
		this.device = device;
		this.user = user;
		this.spotType = spotType;
		this.creationDate = creationDate;
		this.description = description;
		this.name = name;
		this.latitude = latitude;
		this.logitude = logitude;
		this.accuracy = accuracy;
		this.image = image;
		this.isPublic = isPublic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSpot", unique = true, nullable = false)
	public Integer getIdSpot() {
		return this.idSpot;
	}

	public void setIdSpot(Integer idSpot) {
		this.idSpot = idSpot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDevice")
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idType")
	public SpotType getSpotType() {
		return this.spotType;
	}

	public void setSpotType(SpotType spotType) {
		this.spotType = spotType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creationDate", nullable = false, length = 10)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", length = 127)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "latitude", precision = 10, scale = 7)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "logitude", precision = 10, scale = 7)
	public BigDecimal getLogitude() {
		return this.logitude;
	}

	public void setLogitude(BigDecimal logitude) {
		this.logitude = logitude;
	}

	@Column(name = "accuracy", precision = 10, scale = 4)
	public BigDecimal getAccuracy() {
		return this.accuracy;
	}

	public void setAccuracy(BigDecimal accuracy) {
		this.accuracy = accuracy;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "isPublic")
	public Boolean getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

}
