package com.elwin013.arweb.dao.model;

// Generated 2014-12-15 22:55:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpotType generated by hbm2java
 */
@Entity
@Table(name = "SpotType", catalog = "m12173_ar_web")
public class SpotType implements java.io.Serializable {
	private static final long serialVersionUID = -4010429234333621497L;
	
	private Integer idType;
	private String typeName;
	private String typeIcon;
	private Set<Spot> spots = new HashSet<Spot>(0);

	public SpotType() {
	}

	public SpotType(String typeName) {
		this.typeName = typeName;
	}

	public SpotType(String typeName, String typeIcon, Set<Spot> spots) {
		this.typeName = typeName;
		this.typeIcon = typeIcon;
		this.spots = spots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idType", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "typeName", nullable = false, length = 127)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "typeIcon", length = 1024)
	public String getTypeIcon() {
		return this.typeIcon;
	}

	public void setTypeIcon(String typeIcon) {
		this.typeIcon = typeIcon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spotType")
	public Set<Spot> getSpots() {
		return this.spots;
	}

	public void setSpots(Set<Spot> spots) {
		this.spots = spots;
	}

}
