package com.elwin013.arweb.dao.model;

// Generated 2014-12-15 22:55:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "m12173_ar_web")
public class User implements java.io.Serializable {
	private static final long serialVersionUID = -7133273059855508999L;
	
	private Integer idUser;
	private String username;
	private String name;
	private String surname;
	private String password;
	private Set<Authorities> authoritieses = new HashSet<Authorities>(0);
	private Set<Spot> spots = new HashSet<Spot>(0);

	public User() {
	}

	public User(String username, String name, String surname, String password) {
		this.username = username;
		this.name = name;
		this.surname = surname;
		this.password = password;
	}

	public User(String username, String name, String surname, String password,
			Set<Authorities> authoritieses, Set<Spot> spots) {
		this.username = username;
		this.name = name;
		this.surname = surname;
		this.password = password;
		this.authoritieses = authoritieses;
		this.spots = spots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "username", nullable = false, length = 31)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "name", nullable = false, length = 127)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 127)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "password", nullable = false, length = 127)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Authorities> getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set<Authorities> authoritieses) {
		this.authoritieses = authoritieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Spot> getSpots() {
		return this.spots;
	}

	public void setSpots(Set<Spot> spots) {
		this.spots = spots;
	}

}
